# Generated by Django 5.1.2 on 2024-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_backtestresult_alter_stockdata_options_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
