# Generated by Django 5.1.2 on 2024-10-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_prediction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='max_dropdown',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
